OPENAI_API_KEY = "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"

[connections.snowpark]
user = "<KHUSHBOONANDAN>"
password = "<July@123>"
warehouse = "COMPUTE_WH"
role = "MYROLCCOUNTADMIN"
# Find your account info here:
# https://docs.snowflake.com/en/user-guide/admin-account-identifier
account = "fo73265.ap-south-1.aws"
